---
- hosts: yum
  become: yes

  handlers:
    - name: restart plex
      service:
        name: plexmediaserver
        state: restarted

  tasks:
  - name: Upgrade Plex
    yum: 
      name: plexmediaserver 
      state: latest
    notify: restart plex